export const DISCOVER_ITEMS = [
    // --- TOP HITS (EPIC / ENERGETIC) ---
    {
        id: 'd1',
        title: 'One Piece',
        official_cover_url: '/covers/onepiece.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Adventure',
        vibe: 'Epic',
        dialogueDensity: 'High',
        voiceSuitability: 92,
        description: 'The ultimate adventure with a diverse cast. Ideal for experimenting with unique character voices.',
        tags: ['Adventure', 'Shonen', 'Ensemble']
    },
    {
        id: 'd2',
        title: 'Naruto',
        official_cover_url: '/covers/naruto.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Action',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 90,
        description: 'A tale of ninjas, destiny, and friendship. Great for emotive shouting and dramatic monologues.',
        tags: ['Ninjas', 'Shonen', 'Battle']
    },
    {
        id: 'd7',
        title: 'Jujutsu Kaisen',
        official_cover_url: '/covers/jjk28.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Supernatural',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 92,
        description: 'Curses, sorcerers, and urban fantasy. Fast-paced and modern dialogue.',
        tags: ['Curses', 'School', 'Battle']
    },
    {
        id: 'd9',
        title: 'Chainsaw Man',
        official_cover_url: '/covers/csm.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Dark Fantasy',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 89,
        description: 'Chaotic, gore-filled, and surprisingly emotional. Needs a raw, edgy sound profile.',
        tags: ['Gore', 'Demons', 'Fast Paced']
    },
    {
        id: 'd31',
        title: 'Blue Lock',
        official_cover_url: '/covers/bluelock.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Sports',
        vibe: 'Epic',
        dialogueDensity: 'Medium',
        voiceSuitability: 85,
        description: 'Battle royale soccer. Ego-driven dialogue and intensity.',
        tags: ['Soccer', 'Battle', 'Psychological']
    },
    {
        id: 'd41',
        title: 'Tokyo Ghoul',
        official_cover_url: '/covers/tokyoghoul.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Dark Fantasy',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 93,
        description: 'Internal conflict and duality. Needs a voice that can switch between human and monster.',
        tags: ['Ghouls', 'Horror', 'Psychological']
    },
    {
        id: 'd42',
        title: 'Hell\'s Paradise', // Jigokuraku
        official_cover_url: '/covers/jigokuraku.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Dark Fantasy',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 88,
        description: 'Ninjas on a deadly island. Beautiful and brutal.',
        tags: ['Ninjas', 'Island', 'Survival']
    },
    {
        id: 'd43',
        title: 'Black Clover',
        official_cover_url: '/covers/blackclover.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Adventure',
        vibe: 'Energetic',
        dialogueDensity: 'High',
        voiceSuitability: 85,
        description: 'Magic and yelling. Lots of yelling. High energy required.',
        tags: ['Magic', 'Knights', 'Shonen']
    },
    {
        id: 'd3',
        title: 'Bleach',
        official_cover_url: '/covers/bleach.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Action',
        vibe: 'Cinematic',
        dialogueDensity: 'Medium',
        voiceSuitability: 88,
        description: 'Stylish sword fights and supernatural themes. Needs cool, composed voice acting.',
        tags: ['Supernatural', 'Swords', 'Style']
    },
    {
        id: 'd4',
        title: 'Dragon Ball',
        official_cover_url: '/covers/dragonball.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Action',
        vibe: 'Epic',
        dialogueDensity: 'Low',
        voiceSuitability: 85,
        description: 'The grandfather of battle shonen. Focus on screaming, power-ups, and intensity.',
        tags: ['Martial Arts', 'Classic', 'Fighting']
    },
    {
        id: 'd5',
        title: 'Attack on Titan',
        official_cover_url: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Shingeki_no_Kyojin_manga_volume_1.jpg',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Dark Fantasy',
        vibe: 'Epic',
        dialogueDensity: 'Medium',
        voiceSuitability: 95,
        description: 'Grim, political, and intense. Requires a wide range of emotional expression.',
        tags: ['Dark', 'Survival', 'Military']
    },
    {
        id: 'd6',
        title: 'Demon Slayer',
        official_cover_url: 'https://upload.wikimedia.org/wikipedia/en/0/09/Demon_Slayer_-_Kimetsu_no_Yaiba%2C_volume_1.jpg',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Dark Fantasy',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 90,
        description: 'Emotional sword battles against demons. Opportunities for unique demon voices.',
        tags: ['Demons', 'Historical', 'Action']
    },
    {
        id: 'd8',
        title: 'My Hero Academia',
        official_cover_url: 'https://upload.wikimedia.org/wikipedia/en/5/5a/Boku_no_Hero_Academia_Volume_1.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Superhero',
        vibe: 'Energetic',
        dialogueDensity: 'High',
        voiceSuitability: 94,
        description: 'A world of heroes and villains. Massive cast for practicing distinct character voices.',
        tags: ['Heroes', 'School', 'Superpowers']
    },
    {
        id: 'd10',
        title: 'Fullmetal Alchemist',
        official_cover_url: '/covers/fma.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Adventure',
        vibe: 'Epic',
        dialogueDensity: 'High',
        voiceSuitability: 98,
        description: 'A perfect blend of comedy, drama, and action. The gold standard for storytelling.',
        tags: ['Alchemy', 'Military', 'Philosophical']
    },

    // --- SEINEN / CEREBRAL ---
    {
        id: 'd11',
        title: 'Berserk',
        official_cover_url: '/covers/berserk.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Dark Fantasy',
        vibe: 'Epic',
        dialogueDensity: 'Medium',
        voiceSuitability: 88,
        description: 'Heavy themes and intense narration. Requires a deep, gritty narrator setup.',
        tags: ['Dark Fantasy', 'Intense', 'Action']
    },
    {
        id: 'd12',
        title: 'Monster',
        official_cover_url: '/covers/monster.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Crime Drama',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 96,
        description: 'A slow-burning psychological thriller finding a serial killer. Needs nuanced acting.',
        tags: ['Mystery', 'Psychological', 'Serious']
    },
    {
        id: 'd13',
        title: 'Vinland Saga',
        official_cover_url: '/covers/vinlandsaga.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Historical',
        vibe: 'Epic',
        dialogueDensity: 'Medium',
        voiceSuitability: 88,
        description: 'A tale of vikings, revenge, and redemption. Requires strong, grounded vocal performances.',
        tags: ['Historical', 'Vikings', 'Drama']
    },
    {
        id: 'd14',
        title: 'Vagabond',
        official_cover_url: '/covers/vagabond.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Historical',
        vibe: 'Cinematic',
        dialogueDensity: 'Low',
        voiceSuitability: 70,
        description: 'Visual masterpiece about Miyamoto Musashi. Contemplative and quiet.',
        tags: ['Samurai', 'Art', 'Philosophy']
    },
    {
        id: 'd15',
        title: '20th Century Boys',
        official_cover_url: '/covers/20thcenturyboys.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Mystery',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 92,
        description: 'A complex web of conspiracy spanning decades. Great for mystery lovers.',
        tags: ['Mystery', 'Sci-Fi', 'Conspiracy']
    },
    {
        id: 'd16',
        title: 'Goodnight Punpun',
        official_cover_url: '/covers/punpun.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Drama',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 95,
        description: 'Depressing, real, and abstract. A challenging but rewarding acting experience.',
        tags: ['Depression', 'Slice of Life', 'Psychological']
    },
    {
        id: 'd17',
        title: 'Death Note',
        official_cover_url: 'https://upload.wikimedia.org/wikipedia/en/6/6f/Death_Note_Vol_1.jpg',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Thriller',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 95,
        description: 'A deeply psychological cat-and-mouse chase. Perfect for dramatic reading.',
        tags: ['Dialogue Heavy', 'Suspense', 'Smart Protagonist']
    },

    // --- SCI-FI / CINEMATIC ---
    {
        id: 'd18',
        title: 'Akira',
        official_cover_url: '/covers/akira.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Cyberpunk',
        vibe: 'Cinematic',
        dialogueDensity: 'Medium',
        voiceSuitability: 75,
        description: 'The definitive cyberpunk masterpiece. Visuals define the tone, but dialogue drives the revolution.',
        tags: ['Cyberpunk', 'Classic', 'Dystopian']
    },
    {
        id: 'd19',
        title: 'Blame!',
        official_cover_url: '/covers/blame.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Sci-Fi',
        vibe: 'Cinematic',
        dialogueDensity: 'Low',
        voiceSuitability: 60,
        description: 'Atmospheric and visual. Best for immersive soundscapes rather than dialogue.',
        tags: ['Visual Heavy', 'Dark', 'Cyberpunk']
    },
    {
        id: 'd20',
        title: 'Gantz',
        official_cover_url: '/covers/gantz.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Sci-Fi',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 80,
        description: 'Brutal survival game with aliens. Intense action and panic.',
        tags: ['Aliens', 'Survival', 'Gore']
    },
    {
        id: 'd21',
        title: 'Ghost in the Shell',
        official_cover_url: '/covers/gits.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Cyberpunk',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 85,
        description: 'Philosophy meets technology. Dense dialogue about consciousness.',
        tags: ['Cyberpunk', 'Philosophy', 'Police']
    },

    // --- COMEDY / CHILL / ROMANCE ---
    {
        id: 'd22',
        title: 'Spy x Family',
        official_cover_url: '/covers/spyxfamily.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Action/Comedy',
        vibe: 'Chill',
        dialogueDensity: 'Medium',
        voiceSuitability: 98,
        description: 'A unique mix of spy thriller and heartwarming family comedy.',
        tags: ['Spy', 'Wholesome', 'Comedy']
    },
    {
        id: 'd23',
        title: 'Kaguya-sama: Love is War',
        official_cover_url: '/covers/kaguyasama.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'RomCom',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 90,
        description: 'Fast-paced dialogue battles. Great for testing multiple character voices.',
        tags: ['Fast Paced', 'Funny', 'Ensemble Cast']
    },
    {
        id: 'd24',
        title: 'Yotsuba&!',
        official_cover_url: '/covers/yotsuba.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Slice of Life',
        vibe: 'Chill',
        dialogueDensity: 'Medium',
        voiceSuitability: 90,
        description: 'Pure innocence and comedy. Great for a relaxing, light-hearted listening experience.',
        tags: ['Slice of Life', 'Comedy', 'Cute']
    },
    {
        id: 'd25',
        title: 'Nichijou',
        official_cover_url: '/covers/nichijou.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Comedy',
        vibe: 'Energetic',
        dialogueDensity: 'High',
        voiceSuitability: 95,
        description: 'Absurd surrealist comedy. Fast talking and loud reactions required.',
        tags: ['Surreal', 'Comedy', 'School']
    },
    {
        id: 'd26',
        title: 'Komi Can\'t Communicate',
        official_cover_url: '/covers/komi.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Slice of Life',
        vibe: 'Chill',
        dialogueDensity: 'Low',
        voiceSuitability: 70,
        description: 'Quiet moments mixed with loud friends. Heartwarming.',
        tags: ['School', 'Wholesome', 'Romance']
    },
    {
        id: 'd27',
        title: 'Way of the Househusband',
        official_cover_url: '/covers/househusband.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Comedy',
        vibe: 'Chill',
        dialogueDensity: 'Medium',
        voiceSuitability: 90,
        description: 'Yakuza tough guy talk in mundane situations. Hilarious contrast.',
        tags: ['Yakuza', 'Comedy', 'Cooking']
    },
    {
        id: 'd28',
        title: 'Horimiya',
        official_cover_url: '/covers/horimiya.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Romance',
        vibe: 'Chill',
        dialogueDensity: 'Medium',
        voiceSuitability: 90,
        description: 'Realistic high school romance. Natural dialogue flow.',
        tags: ['Romance', 'School', 'Slice of Life']
    },
    {
        id: 'd29',
        title: 'Fruits Basket',
        official_cover_url: '/covers/fruitsbasket.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Shojo',
        vibe: 'Chill',
        dialogueDensity: 'High',
        voiceSuitability: 98,
        description: 'Fantasy romance with deep emotional beats. Excellent for drama.',
        tags: ['Romance', 'Fantasy', 'Drama']
    },

    // --- SPORTS / OTHER ---
    {
        id: 'd30',
        title: 'Haikyuu!!',
        official_cover_url: '/covers/haikyuu.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Sports',
        vibe: 'Energetic',
        dialogueDensity: 'High',
        voiceSuitability: 80,
        description: 'High energy sports action. Lots of shouting, inner monologues, and team dynamics.',
        tags: ['Sports', 'Volleyball', 'Hype']
    },
    {
        id: 'd32',
        title: 'Slam Dunk',
        official_cover_url: '/covers/slamdunk.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Sports',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 88,
        description: 'The definitive basketball manga. Comedy mixed with serious sports.',
        tags: ['Basketball', 'Classic', 'Comedy']
    },
    {
        id: 'd33',
        title: 'Real',
        official_cover_url: '/covers/real.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Drama',
        vibe: 'Cerebral',
        dialogueDensity: 'Medium',
        voiceSuitability: 92,
        description: 'Wheelchair basketball drama. Heavy, emotional, and grounded.',
        tags: ['Sports', 'Drama', 'Disability']
    },
    {
        id: 'd34',
        title: 'Hajime no Ippo',
        official_cover_url: '/covers/ippo.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Sports',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 85,
        description: 'Boxing action with great comedy. Punchy dialogue.',
        tags: ['Boxing', 'Action', 'Comedy']
    },
    {
        id: 'd35',
        title: 'Initial D',
        official_cover_url: '/covers/initiald.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Sports',
        vibe: 'Energetic',
        dialogueDensity: 'Medium',
        voiceSuitability: 75,
        description: 'Street racing legend. Technical jargon mixed with Eurobeat vibes.',
        tags: ['Racing', 'Cars', '90s']
    },
    {
        id: 'd36',
        title: 'Nana',
        official_cover_url: '/covers/nana.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Drama',
        vibe: 'Chill',
        dialogueDensity: 'High',
        voiceSuitability: 98,
        description: 'Music, romance, and heartbreak in Tokyo. Mature and realistic.',
        tags: ['Music', 'Romance', 'Josei']
    },
    {
        id: 'd37',
        title: 'Beck',
        official_cover_url: '/covers/beck.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Music',
        vibe: 'Chill',
        dialogueDensity: 'Medium',
        voiceSuitability: 90,
        description: 'Rock band journey. Gritty and authentic.',
        tags: ['Music', 'Band', 'Growing Up']
    },
    {
        id: 'd38',
        title: 'Your Lie in April',
        official_cover_url: '/covers/yourlieinapril.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Drama',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 98,
        description: 'Classical music tragedy. Poetic monologues.',
        tags: ['Music', 'Romance', 'Sad']
    },
    {
        id: 'd39',
        title: 'Blue Period',
        official_cover_url: '/covers/blueperiod.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Drama',
        vibe: 'Cerebral',
        dialogueDensity: 'High',
        voiceSuitability: 94,
        description: 'The struggle of art school. Deeply introspective.',
        tags: ['Art', 'School', 'Coming of Age']
    },
    {
        id: 'd40',
        title: 'Witch Hat Atelier',
        official_cover_url: '/covers/witchhat.png',
        cover_type: 'volume_1',
        source_verified: true,
        genre: 'Fantasy',
        vibe: 'Chill',
        dialogueDensity: 'Medium',
        voiceSuitability: 92,
        description: 'Whimsical magic system. Wonder-filled dialogue.',
        tags: ['Magic', 'Fantasy', 'Art']
    }
];
